# Generated by Django 4.1.4 on 2022-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspageuser',
            name='newsletterAgree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='locale',
            field=models.CharField(choices=[('en', 'english'), ('jp', 'japanese')], max_length=1024, verbose_name='experiance locale'),
        ),
        migrations.AlterField(
            model_name='initiativeimage',
            name='image_source',
            field=models.ImageField(upload_to='initiative-source-images'),
        ),
    ]
