# Generated by Django 4.1.4 on 2022-12-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_suspageuser_newsletteragree_alter_initiative_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspageuser',
            name='industry',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
