# Generated by Django 4.1.4 on 2022-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_suspageuser_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspageuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
